version: '3.6'
services:
  postgres_db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_USER: compose-postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  walk-dog-backend:
    build: walkdog
    container_name: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  walk-dog-frontend:
    build: angular
    container_name: front_app
    ports:
      - 4200:4200
    depends_on:
      - walk-dog-backend

